# Generated by Django 4.2.5 on 2023-09-19 09:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230919_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца')),
                ('owner_phone_number', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('owner_pure_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region='RU', verbose_name='Нормированный номер владельца')),
                ('have_flats', models.ManyToManyField(db_index=True, related_name='flats_owners', to='property.flat', verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
