# Generated by Django 4.2.5 on 2023-09-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230919_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_phone_number',
            new_name='owner_phone',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone_number',
            new_name='owner_pure_phone',
        ),
    ]
