# Generated by Django 4.2.5 on 2023-09-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0012_rename_owner_phone_number_owner_owner_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complain_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats_complaints', to='property.flat', verbose_name='Квартира, на которую жаловались'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
