# Generated by Django 4.2.5 on 2023-09-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_rename_complainant_complaint_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
