# Generated by Django 4.2.5 on 2023-09-23 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0017_alter_complaint_complain_flat_alter_owner_have_flats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='have_flats',
            new_name='flats',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
